configuration: Release

# restore NuGet packages before running MS Build
before_build:
  - nuget restore
  
image: Visual Studio 2017

# package Web Application project for Web Deploy
build:
  verbosity: minimal
  
artifacts:
  - path: build\tomkamphuis-*.zip