configuration: Release

# restore NuGet packages before running MS Build
before_build:
  - nuget restore
  
image: Visual Studio 2017

# package Web Application project for Web Deploy
build:
  verbosity: normal
  publish_wap_xcopy: true
  
cache:
  - TomKamphuis.Web\node_modules
  
artifacts:
  - path: TomKamphuis.Web
    name: DeploymentPackage
    type: WebDeployPackage